const COMMANDS = [
	{
		cmd: "go test -race -count=1 -v ./...",
		lines: [
			'<span class="t-dim">=== RUN</span>   TestRaceConditions',
			'<span class="t-green">--- PASS:</span> TestRaceConditions (0.11s)',
			'<span class="t-dim">=== RUN</span>   TestAPIDesign',
			'<span class="t-green">--- PASS:</span> TestAPIDesign (0.04s)',
			'<span class="t-dim">=== RUN</span>   TestTelemetry',
			'<span class="t-green">--- PASS:</span> TestTelemetry (0.02s)',
			'<span class="t-dim">=== RUN</span>   TestPerformance',
			'<span class="t-green">--- PASS:</span> TestPerformance (0.02s)',
			'<span class="t-dim">=== RUN</span>   TestSystemProgramming',
			'<span class="t-green">--- PASS:</span> TestSystemProgramming (0.02s)',
			'<span class="t-dim">=== RUN</span>   TestTestingAndCoverage',
			'<span class="t-green">--- PASS:</span> TestTestingAndCoverage (0.02s)',
			'<span class="t-green">PASS</span>',
			'<span class="t-green">ok  </span>  github.com/bandarji/jell.c/internal/machine  <span class="t-dim">0.184s</span>',
		],
	},
	{
		cmd: "cargo build --release",
		lines: [
			'<span class="t-green">Compiling</span> jell-c v0.1.0 (/src/project/rs/jell-c)',
			'<span class="t-peach">warning</span><span class="t-dim">: unused import: `youtube::launch`</span>',
			'<span class="t-dim"> --> src/main.rs:4:5</span>',
			'<span class="t-dim">  |</span>',
			'<span class="t-dim">4 | use youtube::launch;</span>',
			'<span class="t-dim">  |     ^^^^^^^^^^^^^^^</span>',
			'<span class="t-dim">  = note: coming soon</span>',
			"",
			'    <span class="t-green">Finished</span> `release` profile [optimized] target(s) in 2.41s',
		],
	},
	{
		cmd: "ls -l content/",
		lines: [
			'<span class="t-dim">total 3</span>',
			'<span class="t-cyan">drwxr-xr-x</span>  youtube/     <span class="t-pink">coming soon</span>   advanced programming lectures',
			'<span class="t-cyan">drwxr-xr-x</span>  free/        <span class="t-green">public</span>        videos, notes, source code',
			'<span class="t-cyan">drwxr-xr-x</span>  paid/        <span class="t-peach">enroll</span>        full source, problem sets',
			'<span class="t-cyan">drwxr-xr-x</span>  training/    <span class="t-green">engagements</span>   teams that already ship',
		],
	},
	{
		cmd: "curl -x '' --http1.0 --ipv4 --silent --connect-timeout 5 http://jell.c/",
		lines: [
			'<span class="t-green">   _   ___   _   _      ___</span>',
			'<span class="t-green">  (_) | __| | | | |    / __|</span>',
			'<span class="t-green">  | | | _|  | | | |   | (__</span>',
			'<span class="t-green"> _/ | |___| |_| |_| _  \\___|</span>',
			'<span class="t-green">|__/               (_)</span>',
			"",
			'<span class="t-peach">  advanced programming concepts</span>',
			'<span class="t-dim">  youtube  ·  courses  ·  corporate training</span>',
		],
	},
	{
		cmd: "minicom jell-c",
		lines: [
			'<span class="t-dim">Welcome to minicom 2.9</span>',
			'<span class="t-dim">Port /dev/ttyS0, 14400 8N1</span>',
			"",
			"ATDT555-5355",
			'<span class="t-green">CONNECT 14400/ARQ/V.32bis</span>',
			"",
			'<span class="t-cyan">  -=[ JELL.C BBS ]=-</span>  <span class="t-dim">node 1/4</span>',
			"",
			'      <span class="t-green">███</span>           <span class="t-peach">████</span>  <span class="t-pink">████</span>',
			'     <span class="t-green">░░░</span>           <span class="t-peach">░░███</span> <span class="t-pink">░░███</span>',
			'     <span class="t-green">█████</span>  <span class="t-cyan">██████</span>  <span class="t-peach">░███</span>  <span class="t-pink">░███</span>      <span class="t-green">██████</span>',
			'    <span class="t-green">░░███</span>  <span class="t-cyan">███░░███</span> <span class="t-peach">░███</span>  <span class="t-pink">░███</span>     <span class="t-green">███░░███</span>',
			'     <span class="t-green">░███</span> <span class="t-cyan">░███████</span>  <span class="t-peach">░███</span>  <span class="t-pink">░███</span>    <span class="t-green">░███ ░░░</span>',
			'     <span class="t-green">░███</span> <span class="t-cyan">░███░░░</span>   <span class="t-peach">░███</span>  <span class="t-pink">░███</span>    <span class="t-green">░███  ███</span>',
			'     <span class="t-green">░███</span> <span class="t-cyan">░░██████</span>  <span class="t-peach">█████</span> <span class="t-pink">█████</span> <span class="t-dim">██</span><span class="t-green">░░██████</span>',
			'     <span class="t-green">░███</span>  <span class="t-cyan">░░░░░░</span>  <span class="t-peach">░░░░░</span> <span class="t-pink">░░░░░</span> <span class="t-dim">░░</span>  <span class="t-green">░░░░░░</span>',
			' <span class="t-green">███ ░███</span>',
			'<span class="t-green">░░██████</span>',
			' <span class="t-green">░░░░░░</span>',
			"",
			'  <span class="t-green">[M]</span>ail     <span class="t-green">[F]</span>iles     <span class="t-green">[C]</span>ontent',
			'  <span class="t-green">[T]</span>raining <span class="t-pink">[Y]</span>outube <span class="t-dim">offline</span>  <span class="t-green">[G]</span>oodbye',
			"",
			'<span class="t-dim">Caller #18421 · 47 minutes remaining</span> <span class="t-peach">Command?</span>',
		],
	},
	{
		cmd: "head -n 11 src/jell.c",
		lines: [
			'<span class="t-dim">/* jell.c — site routes */</span>',
			'<span class="t-peach">#ifndef</span> JELL_C',
			'<span class="t-peach">#define</span> JELL_C',
			"",
			'<span class="t-peach">#define</span> HOME      <a href="index.html">"index.html"</a>',
			'<span class="t-peach">#define</span> VIDEOS    <a href="videos">"videos"</a>',
			'<span class="t-peach">#define</span> CONTENT   <a href="content">"content"</a>',
			'<span class="t-peach">#define</span> TRAINING  <a href="training">"training"</a>',
			'<span class="t-peach">#define</span> CONTACT   <a href="contact">"contact"</a>',
			"",
			'<span class="t-peach">#endif</span> <span class="t-dim">/* JELL_C */</span>',
		],
	},
	{
		cmd: "cat training/brief.txt",
		lines: [
			'<span class="t-peach">Software development training for engineering orgs.</span>',
			"",
			"  format     on-site or remote",
			"  length     1-day workshop  →  multi-week cohort",
			"  focus      systems, language internals, test-driven development, concurrency",
			"  audience   teams that already ship",
			"",
			'<span class="t-dim"># not a bootcamp. not slides about agile.</span>',
		],
	},
	{
		cmd: "cargo test",
		lines: [
			'    <span class="t-green">Finished</span> `test` profile [unoptimized + debuginfo] target(s) in 0.12s',
			'     <span class="t-green">Running</span> unittests src/lib.rs (target/debug/deps/jell_c-7a2c91e4)',
			"",
			"running 4 tests",
			'test api::design ... <span class="t-green">ok</span>',
			'test concurrency::no_races ... <span class="t-green">ok</span>',
			'test youtube::launch ... <span class="t-pink">ignored</span><span class="t-dim">, coming soon</span>',
			"",
			'<span class="t-green">test result: ok.</span> 3 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.01s',
		],
	},
	{
		cmd: "uv sync --frozen && uv run pytest",
		lines: [
			'<span class="t-green">Resolved</span> 11 packages in 6ms',
			'<span class="t-green">Audited</span> 11 packages in 1ms',
			"",
			'<span class="t-dim">============================= test session starts ==============================</span>',
			"collected 4 items",
			"",
			'test_refcount.py ..                                               <span class="t-dim">[ 50%]</span>',
			'test_gil.py .                                                     <span class="t-dim">[ 75%]</span>',
			'test_youtube.py s                                                 <span class="t-dim">[100%]</span>',
			"",
			'<span class="t-green">3 passed</span><span class="t-dim">, </span><span class="t-pink">1 skipped</span> <span class="t-dim">in 0.09s</span>',
		],
	},
	{
		cmd: "uv run uvicorn app.main:app --reload --port 8000",
		lines: [
			'<span class="t-green">INFO:</span>     Will watch for changes in these directories: [\'/src/jell.c\']',
			'<span class="t-green">INFO:</span>     Uvicorn running on <span class="t-cyan">http://127.0.0.1:8000</span> (Press CTRL+C to quit)',
			'<span class="t-green">INFO:</span>     Started reloader process [18421] using WatchFiles',
			'<span class="t-green">INFO:</span>     Started server process [18423]',
			'<span class="t-green">INFO:</span>     Waiting for application startup.',
			'<span class="t-green">INFO:</span>     Application startup complete.',
			'<span class="t-green">INFO:</span>     127.0.0.1:53102 - "GET /docs HTTP/1.1" <span class="t-green">200 OK</span>',
			'<span class="t-green">INFO:</span>     127.0.0.1:53103 - "GET /youtube HTTP/1.1" <span class="t-pink">404 Not Found</span>',
		],
	},
	{
		cmd: "tcpdump -nn -q -r traces/jell.pcap -c 8",
		lines: [
			'<span class="t-dim">14:22:01.10001</span> IP 203.0.113.10.53100 &gt; 1.1.1.1.53: UDP, length 24',
			'<span class="t-dim">14:22:01.10009</span> IP 1.1.1.1.53 &gt; 203.0.113.10.53100: UDP, length 40',
			'<span class="t-dim">14:22:01.10234</span> IP 203.0.113.10.53102 &gt; 198.51.100.80.80: tcp 0',
			'<span class="t-dim">14:22:01.10241</span> IP 198.51.100.80.80 &gt; 203.0.113.10.53102: tcp 0',
			'<span class="t-dim">14:22:01.10400</span> IP 203.0.113.10.53102 &gt; 198.51.100.80.80: tcp 73: <span class="t-cyan">HTTP: GET / HTTP/1.1</span>',
			'<span class="t-dim">14:22:01.10411</span> IP 198.51.100.80.80 &gt; 203.0.113.10.53102: tcp 128: <span class="t-green">HTTP: HTTP/1.1 200 OK</span>',
			'<span class="t-dim">14:22:01.10520</span> IP 203.0.113.10.53104 &gt; 198.51.100.80.80: tcp 81: <span class="t-cyan">HTTP: GET /youtube HTTP/1.1</span>',
			'<span class="t-dim">14:22:01.10528</span> IP 198.51.100.80.80 &gt; 203.0.113.10.53104: tcp 90: <span class="t-pink">HTTP: HTTP/1.1 404 Not Found</span>',
		],
	},
	{
		cmd: "helm upgrade --install jell-c ./chart -n jell-c --create-namespace --wait",
		lines: [
			'Release "jell-c" does not exist. Installing it now.',
			"NAME: jell-c",
			"LAST DEPLOYED: Thu Sep  3 14:16:00 2026",
			"NAMESPACE: jell-c",
			'STATUS: <span class="t-green">deployed</span>',
			"REVISION: 1",
			'<span class="t-dim">TEST SUITE: None</span>',
			'<span class="t-peach">NOTES:</span>',
			"  web       ClusterIP  80/tcp",
			"  api       ClusterIP  8000/tcp",
			'  youtube   <span class="t-pink">pending</span>    coming soon',
		],
	},
	{
		cmd: "git log --oneline --decorate -n 8",
		lines: [
			'<span class="t-peach">c4e91a2</span> <span class="t-cyan">(HEAD -> </span><span class="t-green">main</span><span class="t-cyan">)</span> <span class="t-dim">feat:</span> wrote python module in go, for py import',
			'<span class="t-peach">9b12f03</span> <span class="t-dim">doc:</span> deep understanding of rust macros',
			'<span class="t-peach">7a80d1c</span> <span class="t-dim">test:</span> testing and coverage',
			'<span class="t-peach">2f7d1aa</span> <span class="t-dim">doc:</span> deep understanding of go internals',
			'<span class="t-peach">e31c8b4</span> <span class="t-dim">feat:</span> added free video content',
			'<span class="t-peach">a19b6e0</span> <span class="t-dim">feat!:</span> maximum concurrency',
			'<span class="t-peach">d5f02c8</span> <span class="t-dim">doc:</span> designed the API',
			'<span class="t-peach">b0e2ed8</span> Initial commit',
		],
	},
	{
		cmd: "cat videos/STATUS",
		lines: [
			'<span class="t-pink">coming soon</span>',
			"",
			"Editing the jell.c YouTube channel.",
			"First series: Test-Driven Development.",
			"",
			'<span class="t-dim">watch this space.</span>',
		],
	},
];
